language: objective-c
osx_image: xcode10.1
branches:
  only:
    - master
before_install:
 - brew update
 - carthage bootstrap --no-use-binaries --platform iOS

script: xcodebuild -scheme NeatoSDK test -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.0' | xcpretty && exit ${PIPESTATUS[0]}

