language: objective-c
osx_image: xcode7.3
branches:
  only:
    - master
before_install:
 - brew update
 - carthage bootstrap --use-submodules --platform iOS
script: xctool -workspace NeatoSDK.xcworkspace/ -scheme NeatoSDK test -sdk iphonesimulator
