language: objective-c
osx_image: xcode7.3
before_install:
 - brew update
 - brew install carthage
 - carthage bootstrap --use-submodules --platform iOS
script: xctool -workspace NeatoSDK.xcworkspace/ -scheme NeatoSDK test -sdk iphonesimulator
